- name: Deploy Docker Container

  hosts: localhost

  tasks:
    - name: stop existing container
      command: docker stop tomcat
      ignore_errors: yes
    - name: remove container
      command: docker rm tomcat
      ignore_errors: yes
    - name: remove existing image
      command: docker rmi kunle314/kunle314/my-tomcat-app:final-version-2025b
      ignore_errors: yes
    - name: create docker container using new Image
      command: docker run -d --name tomcat -p 8083:8080 kunle314/my-tomcat-app:final-version-2025b
